### ISSUE TITLE
Scrollbar styling

### ISSUE THREAD

**Issue by zimejin** [AndresXI/Netflix-Clone#1]
Awesome project,  But I noticed the horizontal scrollbars aren't having their styles applied.

**Comment by AndresXI** [comment]
Yeah, I still have not figured this one out yet. If you or anyone else can fix this please submit a pull request asap! thanks.

**Comment by AndresXI** [comment]
> Awesome project, But I noticed the horizontal scrollbars aren't having their styles applied.

Yeah, I still have not figured this one out yet. If you or anyone else can fix this please submit a pull request asap! thanks.

**Comment by trblackw** [comment]
@AndresXI I submitted a PR addressing this.

**Comment by AndresXI** [comment]
> @AndresXI I submitted a PR addressing this.

Nice, thanks!
